### PR TITLE
Fixes GH-8

### PR DESCRIPTION
**Pull request by goatslacker**
Also removes a bunch of whitespace.

### CODE REVIEW

**Comment by WolfgangKluge** [comment]
_Also removes a bunch of whitespace_ - don't really like it (my editor adds those whitespace-only lines) - maybe I need a new one (any suggestions for windows and linux) ;)

No action needed - if I want them, I will re-add them after merge...

**Comment by goatslacker** [comment]
My editor removes extra whitespace when I save a file. I use ViM which works out well. You may be able to configure your editor to run scripts post save. I use this RegExp `s/\s\+$//ge`

Which editor are you using now?

Oh and I didn't understand the last line, are you referring to the whitespace? I can add it back to this pull request.

**Comment by WolfgangKluge** [comment]
No, don't add anything. It's merged (with some modifications) now, but not in master (3fc67d032032c26cec5cdb8ecca137220a15e639 branch multiple-files). There are some last (hopefully) problems with the test helpers.
I renamed some property names, too (e.g. "covered" instead of "tested" and "coverage" instead of "total")..

I use Visual Studio and Notepad++ on Windows and jEdit on Linux (but I'm not satisfied).

**Comment by goatslacker** [comment]
I've heard good things about [Aptana](http://aptana.com/) and [Sublime](http://www.sublimetext.com/2) they're both cross platform and worth looking into.

**Comment by WolfgangKluge** [comment]
Thanks for pull request ;)

**Pull request merged**
